# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d4e750cf4d70825e2d6c6979e8752d8"
name = "inventory-app"
handle = "inventory-app-48"
application_url = "https://adds-texts-employment-zoning.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6f0f0aa9.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://adds-texts-employment-zoning.trycloudflare.com/auth/callback",
  "https://adds-texts-employment-zoning.trycloudflare.com/auth/shopify/callback",
  "https://adds-texts-employment-zoning.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
